[package]
name    = "freeflow-rewards-v2"
version = "2.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
idl-build = []

[dependencies]
solana-program = { workspace = true }
borsh          = { workspace = true }
spl-token      = { workspace = true }

[dev-dependencies]
solana-program-test = { workspace = true }
solana-sdk          = { workspace = true }
tokio               = { workspace = true }
